apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-projection
  namespace: wittgenstein
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elasticsearch-projection
  template:
    metadata:
      labels:
        app: elasticsearch-projection
    spec:
      containers:
        - name: elasticsearch-projection
          image: registry.mainframe-0:32000/wittgenstein/tools:0.1.0-491510a-20200712T1713240200
          command: ["/elasticsearch-projection"]
          args:
            - "--elasticsearch-url"
            - "http://elasticsearch.foundation.svc.cluster.local:9200"
            - "--factdb-url"
            - "http://factdb.wittgenstein.svc.cluster.local"
            - "--index-name"
            - "dev.wittgenstein.entities"
            - "--kafka-group-id"
            - "0"


