# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schemata/protobuf/wittgenstein/factdb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schemata/protobuf/wittgenstein/factdb.proto',
  package='dev.abstractmachines.wittgenstein',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+schemata/protobuf/wittgenstein/factdb.proto\x12!dev.abstractmachines.wittgenstein\"\x17\n\x15ProjectionDescription\"\xa4\x01\n\x0fProjectedEntity\x12\x12\n\nentity_uri\x18\x01 \x01(\t\x12N\n\x06\x66ields\x18\x02 \x03(\x0b\x32>.dev.abstractmachines.wittgenstein.ProjectedEntity.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x10StateFactRequest\x12\x12\n\nentity_uri\x18\x02 \x01(\t\x12\x12\n\nsource_uri\x18\x03 \x01(\t\x12\x11\n\tfield_uri\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\t\"A\n\x0eStateFactReply\x12\x12\n\x08\x66\x61\x63t_uri\x18\x01 \x01(\tH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\n\n\x08response\"\x15\n\x13LookupEntityRequest\"\x13\n\x11LookupEntityReply2\xf8\x03\n\x06\x46\x61\x63tDB\x12u\n\tStateFact\x12\x33.dev.abstractmachines.wittgenstein.StateFactRequest\x1a\x31.dev.abstractmachines.wittgenstein.StateFactReply\"\x00\x12z\n\nStateFacts\x12\x33.dev.abstractmachines.wittgenstein.StateFactRequest\x1a\x31.dev.abstractmachines.wittgenstein.StateFactReply\"\x00(\x01\x30\x01\x12~\n\x0cLookupEntity\x12\x36.dev.abstractmachines.wittgenstein.LookupEntityRequest\x1a\x34.dev.abstractmachines.wittgenstein.LookupEntityReply\"\x00\x12{\n\x07Project\x12\x38.dev.abstractmachines.wittgenstein.ProjectionDescription\x1a\x32.dev.abstractmachines.wittgenstein.ProjectedEntity\"\x00\x30\x01\x62\x06proto3'
)




_PROJECTIONDESCRIPTION = _descriptor.Descriptor(
  name='ProjectionDescription',
  full_name='dev.abstractmachines.wittgenstein.ProjectionDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=105,
)


_PROJECTEDENTITY_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='dev.abstractmachines.wittgenstein.ProjectedEntity.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dev.abstractmachines.wittgenstein.ProjectedEntity.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dev.abstractmachines.wittgenstein.ProjectedEntity.FieldsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=272,
)

_PROJECTEDENTITY = _descriptor.Descriptor(
  name='ProjectedEntity',
  full_name='dev.abstractmachines.wittgenstein.ProjectedEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_uri', full_name='dev.abstractmachines.wittgenstein.ProjectedEntity.entity_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fields', full_name='dev.abstractmachines.wittgenstein.ProjectedEntity.fields', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROJECTEDENTITY_FIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=272,
)


_STATEFACTREQUEST = _descriptor.Descriptor(
  name='StateFactRequest',
  full_name='dev.abstractmachines.wittgenstein.StateFactRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_uri', full_name='dev.abstractmachines.wittgenstein.StateFactRequest.entity_uri', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_uri', full_name='dev.abstractmachines.wittgenstein.StateFactRequest.source_uri', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_uri', full_name='dev.abstractmachines.wittgenstein.StateFactRequest.field_uri', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dev.abstractmachines.wittgenstein.StateFactRequest.value', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=366,
)


_STATEFACTREPLY = _descriptor.Descriptor(
  name='StateFactReply',
  full_name='dev.abstractmachines.wittgenstein.StateFactReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fact_uri', full_name='dev.abstractmachines.wittgenstein.StateFactReply.fact_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='dev.abstractmachines.wittgenstein.StateFactReply.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='dev.abstractmachines.wittgenstein.StateFactReply.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=368,
  serialized_end=433,
)


_LOOKUPENTITYREQUEST = _descriptor.Descriptor(
  name='LookupEntityRequest',
  full_name='dev.abstractmachines.wittgenstein.LookupEntityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=456,
)


_LOOKUPENTITYREPLY = _descriptor.Descriptor(
  name='LookupEntityReply',
  full_name='dev.abstractmachines.wittgenstein.LookupEntityReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=477,
)

_PROJECTEDENTITY_FIELDSENTRY.containing_type = _PROJECTEDENTITY
_PROJECTEDENTITY.fields_by_name['fields'].message_type = _PROJECTEDENTITY_FIELDSENTRY
_STATEFACTREPLY.oneofs_by_name['response'].fields.append(
  _STATEFACTREPLY.fields_by_name['fact_uri'])
_STATEFACTREPLY.fields_by_name['fact_uri'].containing_oneof = _STATEFACTREPLY.oneofs_by_name['response']
_STATEFACTREPLY.oneofs_by_name['response'].fields.append(
  _STATEFACTREPLY.fields_by_name['error'])
_STATEFACTREPLY.fields_by_name['error'].containing_oneof = _STATEFACTREPLY.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['ProjectionDescription'] = _PROJECTIONDESCRIPTION
DESCRIPTOR.message_types_by_name['ProjectedEntity'] = _PROJECTEDENTITY
DESCRIPTOR.message_types_by_name['StateFactRequest'] = _STATEFACTREQUEST
DESCRIPTOR.message_types_by_name['StateFactReply'] = _STATEFACTREPLY
DESCRIPTOR.message_types_by_name['LookupEntityRequest'] = _LOOKUPENTITYREQUEST
DESCRIPTOR.message_types_by_name['LookupEntityReply'] = _LOOKUPENTITYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProjectionDescription = _reflection.GeneratedProtocolMessageType('ProjectionDescription', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTIONDESCRIPTION,
  '__module__' : 'schemata.protobuf.wittgenstein.factdb_pb2'
  # @@protoc_insertion_point(class_scope:dev.abstractmachines.wittgenstein.ProjectionDescription)
  })
_sym_db.RegisterMessage(ProjectionDescription)

ProjectedEntity = _reflection.GeneratedProtocolMessageType('ProjectedEntity', (_message.Message,), {

  'FieldsEntry' : _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROJECTEDENTITY_FIELDSENTRY,
    '__module__' : 'schemata.protobuf.wittgenstein.factdb_pb2'
    # @@protoc_insertion_point(class_scope:dev.abstractmachines.wittgenstein.ProjectedEntity.FieldsEntry)
    })
  ,
  'DESCRIPTOR' : _PROJECTEDENTITY,
  '__module__' : 'schemata.protobuf.wittgenstein.factdb_pb2'
  # @@protoc_insertion_point(class_scope:dev.abstractmachines.wittgenstein.ProjectedEntity)
  })
_sym_db.RegisterMessage(ProjectedEntity)
_sym_db.RegisterMessage(ProjectedEntity.FieldsEntry)

StateFactRequest = _reflection.GeneratedProtocolMessageType('StateFactRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEFACTREQUEST,
  '__module__' : 'schemata.protobuf.wittgenstein.factdb_pb2'
  # @@protoc_insertion_point(class_scope:dev.abstractmachines.wittgenstein.StateFactRequest)
  })
_sym_db.RegisterMessage(StateFactRequest)

StateFactReply = _reflection.GeneratedProtocolMessageType('StateFactReply', (_message.Message,), {
  'DESCRIPTOR' : _STATEFACTREPLY,
  '__module__' : 'schemata.protobuf.wittgenstein.factdb_pb2'
  # @@protoc_insertion_point(class_scope:dev.abstractmachines.wittgenstein.StateFactReply)
  })
_sym_db.RegisterMessage(StateFactReply)

LookupEntityRequest = _reflection.GeneratedProtocolMessageType('LookupEntityRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPENTITYREQUEST,
  '__module__' : 'schemata.protobuf.wittgenstein.factdb_pb2'
  # @@protoc_insertion_point(class_scope:dev.abstractmachines.wittgenstein.LookupEntityRequest)
  })
_sym_db.RegisterMessage(LookupEntityRequest)

LookupEntityReply = _reflection.GeneratedProtocolMessageType('LookupEntityReply', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPENTITYREPLY,
  '__module__' : 'schemata.protobuf.wittgenstein.factdb_pb2'
  # @@protoc_insertion_point(class_scope:dev.abstractmachines.wittgenstein.LookupEntityReply)
  })
_sym_db.RegisterMessage(LookupEntityReply)


_PROJECTEDENTITY_FIELDSENTRY._options = None

_FACTDB = _descriptor.ServiceDescriptor(
  name='FactDB',
  full_name='dev.abstractmachines.wittgenstein.FactDB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=480,
  serialized_end=984,
  methods=[
  _descriptor.MethodDescriptor(
    name='StateFact',
    full_name='dev.abstractmachines.wittgenstein.FactDB.StateFact',
    index=0,
    containing_service=None,
    input_type=_STATEFACTREQUEST,
    output_type=_STATEFACTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StateFacts',
    full_name='dev.abstractmachines.wittgenstein.FactDB.StateFacts',
    index=1,
    containing_service=None,
    input_type=_STATEFACTREQUEST,
    output_type=_STATEFACTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LookupEntity',
    full_name='dev.abstractmachines.wittgenstein.FactDB.LookupEntity',
    index=2,
    containing_service=None,
    input_type=_LOOKUPENTITYREQUEST,
    output_type=_LOOKUPENTITYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Project',
    full_name='dev.abstractmachines.wittgenstein.FactDB.Project',
    index=3,
    containing_service=None,
    input_type=_PROJECTIONDESCRIPTION,
    output_type=_PROJECTEDENTITY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACTDB)

DESCRIPTOR.services_by_name['FactDB'] = _FACTDB

# @@protoc_insertion_point(module_scope)
